---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  labels:
    app: jenkins
  namespace: qa
spec:
  schedule: '* * * * *'
  jobTemplate:
    metadata:
      labels:
        preprod: devops
    spec:
      template:
        metadata:
          labels:
            preprod: devops
        spec:
          restartPolicy: OnFailure
          containers:
            - name: jenkins
              image: jenkins/jenkins
              ports:
                - containerPort: 8080
  