---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
spec:
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels: 
        app: test
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          args:
            - sleep
            - 50s