---
apiVersion: batch/v1
kind: Job
metadata:
  name: job
  labels:
    app: nginx 
  namespace: devops
spec:
  template:
    metadata:
      labels:
        preprod: devops
    spec:
      restartPolicy: OnFailure 
      containers:
        - name: nginx
          image: nginx 
          ports:
            - containerPort: 80
            