---
apiVersion: v1
kind: Pod
metadata:
  name: devops 
spec:
  containers:
    - name:
      image: neelima456/nopcommerce:latest
      args:
        sleep
        1d

        




          

     



