---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dev-pod
spec:
  minReadySeconds: 1
  replicas: 2
  selector:
    matchLabels:
      dev: pre-prod
  template:
    metadata:
      labels:
        dev: pre-prod
    spec:
      containers:
        - name: nop
          image: neelima456/nopcommerce:latest
          args:
            - sleep
            - 1d
          ports:
            - containerPort: 5000