---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
  labels:
    app: qa
spec:
  containers:
    - name: jenkins
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-1
  labels:
    app: qa
spec:
  containers:
    - name: jenkins
      image: nginx
      ports:
       - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-2
  labels:
    app: qa
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins
      ports:
       - containerPort: 8080
      
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-3
  labels:
    app: qa
spec:
  containers:
    - name: jenkins
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-4
  labels:
    app: qa
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins
      ports:
         - containerPort: 8080

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    app: qa
spec:
  minReadySeconds: 2
  replicas: 10
  selector:
    matchLabels:
      laptop: keyboard
  template:
    metadata:
      name: labels
      labels:
        laptop: keyboard
    spec:
      containers:
        - name: replicas
          image: jenkins/jenkins
          ports:
            - containerPort: 8080