---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
  labels:
    app: qa
spec:
  containers:
    - name: jenkins
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-1
  labels:
    app: qa
spec:
  containers:
    - name: jenkins
      image: nginx
      ports:
       - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-2
  labels:
    app: qa
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins
      ports:
       - containerPort: 8080
      
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-3
  labels:
    app: qa
spec:
  containers:
    - name: jenkins
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-4
  labels:
    app: qa
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins
      ports:
         - containerPort: 8080