---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-2
  labels:
    dev: cloud
spec:
  minReadySeconds:
  selector:
    matchExpressions:
      - key: dev
        operator: In
        values:
          -app
          -pre-prod
      - key: prod
        operator:NotIn
        values:
          - qa
          - env
  replicas: 2          
  template:
    metadata:
      labels:
       devops-version
    spec:
      containers:
        - name: replicas
          image: jenkins/jenkins
          ports::
            - containerPort: 


---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    aws: devops
    prod: devops-version
   type: NodePort
   ports:
     - port: 80
       targetport: 8080 
