---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-1
  labels:
    dev: cloud
spec:
  minReadySeconds: 2
  replicas: 1
  selector:
    matchLabels:
      dev: cloud
  template:
    metadata:
      name: labels
      labels:
        dev: cloud
    spec:
      containers:
        - name: replicas
          image: jenkins/jenkins
          ports:
            - containerPort: 8080