---
apiVersion: v1
kind: ReplicationController
metadata:
  name: devops
spec:
  replicas: 1
  selector:
    app: devops
  template:
    metadata:
      labels:
        apps: devops
    spec:
      containers:
        - name: devops
          image: nginx/nginx-ingress
          ports:
            - containerPort: 80

          
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  selector:
    apps: devops
  ports:
    - portcol:
      port: 80
      targetport: 80
    



                  
    
      
    




