---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    dev: cloud
spec:
  minReadySeconds: 2
  selector:
    matchExpressions:
      - key: dev
        operator: In
        values:
          - app
          - pre-prod
      - key: prod
        operator: NotIn
        values:
          - qa
          - env
  replicas: 2          
  template:
    metadata:
      labels:
        dev: app
        prod: cloud
    spec:
      containers:
        - name: replicas
          image: jenkins/jenkins
          ports:
            - containerPort: 8080 
              name: svc


---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    dev: app
    prod: cloud

    
  type: NodePort
  ports:
    - port: 8080
      targetPort: svc


