---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  selector:
    app: gcp
    network: natgateway
    devops: git
    databases: oracledb 
  ports:
    - name: httpd
      port: 80
      protocol: TCP
      targetPort: httpd
      nodePort: 31000
    - name: tomcat
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31001