---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  selector:
    app: gcp
    network: natgateway
    devops: git
    databases: oracledb 
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: nginx
      nodePort: 31003
    - name: nop
      port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 31001